/*
 *
 * Dapps constants
 *
 */

enum ActionTypes {
  FETCH_DAPPS_REQUEST = '@@dapps/Dapps/FETCH_DAPPS_REQUEST',
  FETCH_DAPPS_SUCCESS = '@@dapps/Dapps/FETCH_DAPPS_SUCCESS',
  FETCH_DAPPS_FAILURE = '@@dapps/Dapps/FETCH_DAPPS_FAILURE',

  CREATE_DAPP_REQUEST = '@@dapps/Dapps/CREATE_DAPP_REQUEST',
  CREATE_DAPP_SUCCESS = '@@dapps/Dapps/CREATE_DAPP_SUCCESS',
  CREATE_DAPP_FAILURE = '@@dapps/Dapps/CREATE_DAPP_FAILURE',

  UPDATE_DAPP_REQUEST = '@@dapps/Dapps/UPDATE_DAPP_REQUEST',
  UPDATE_DAPP_SUCCESS = '@@dapps/Dapps/UPDATE_DAPP_SUCCESS',
  UPDATE_DAPP_FAILURE = '@@dapps/Dapps/UPDATE_DAPP_FAILURE',

  UPVOTE_DAPP_REQUEST = '@@dapps/Dapps/UPVOTE_DAPP_REQUEST',
  UPVOTE_DAPP_SUCCESS = '@@dapps/Dapps/UPVOTE_DAPP_SUCCESS',
  UPVOTE_DAPP_FAILURE = '@@dapps/Dapps/UPVOTE_DAPP_FAILURE',

  DOWNVOTE_DAPP_REQUEST = '@@dapps/Dapps/DOWNVOTE_DAPP_REQUEST',
  DOWNVOTE_DAPP_SUCCESS = '@@dapps/Dapps/DOWNVOTE_DAPP_SUCCESS',
  DOWNVOTE_DAPP_FAILURE = '@@dapps/Dapps/DOWNVOTE_DAPP_FAILURE',

  UPDATE_DAPP_DATA_REQUEST = '@@dapps/Dapps/UPDATE_DAPP_DATA_REQUEST',
  UPDATE_DAPP_DATA_SUCCESS = '@@dapps/Dapps/UPDATE_DAPP_DATA_SUCCESS',
  UPDATE_DAPP_DATA_FAILURE = '@@dapps/Dapps/UPDATE_DAPP_DATA_FAILURE',

  WITHDRAW_REQUEST = '@@dapps/Dapps/WITHDRAW_REQUEST',
  WITHDRAW_SUCCESS = '@@dapps/Dapps/WITHDRAW_SUCCESS',
  WITHDRAW_FAILURE = '@@dapps/Dapps/WITHDRAW_FAILURE',

  SET_LOADING = '@@dapps/Dapps/SET_LOADING',
}

export default ActionTypes;
