/*
 *
 * Dapps constants
 *
 */

enum ActionTypes {
  CREATE_DAPP_REQUEST = '@@dapps/Dapps/CREATE_DAPP_REQUEST',
  CREATE_DAPP_SUCCESS = '@@dapps/Dapps/CREATE_DAPP_SUCCESS',
  CREATE_DAPP_FAILURE = '@@dapps/Dapps/CREATE_DAPP_FAILURE',

  UPDATE_DAPP_REQUEST = '@@dapps/Dapps/UPDATE_DAPP_REQUEST',
  UPDATE_DAPP_SUCCESS = '@@dapps/Dapps/UPDATE_DAPP_SUCCESS',
  UPDATE_DAPP_FAILURE = '@@dapps/Dapps/UPDATE_DAPP_FAILURE',

  UPVOTE_DAPP_REQUEST = '@@dapps/Dapps/UPVOTE_DAPP_REQUEST',
  UPVOTE_DAPP_SUCCESS = '@@dapps/Dapps/UPVOTE_DAPP_SUCCESS',
  UPVOTE_DAPP_FAILURE = '@@dapps/Dapps/UPVOTE_DAPP_FAILURE',

  DOWNVOTE_DAPP_REQUEST = '@@dapps/Dapps/DOWNVOTE_DAPP_REQUEST',
  DOWNVOTE_DAPP_SUCCESS = '@@dapps/Dapps/DOWNVOTE_DAPP_SUCCESS',
  DOWNVOTE_DAPP_FAILURE = '@@dapps/Dapps/DOWNVOTE_DAPP_FAILURE',
}

export default ActionTypes;
