import EmbarkJS from '../embarkjs'
let MiniMeTokenInterfaceJSONConfig = {
  contract_name: {
    className: 'MiniMeTokenInterface',
    args: [],
    code: '',
    runtimeBytecode: '',
    realRuntimeBytecode: '',
    linkReferences: {},
    swarmHash: '',
    gasEstimates: null,
    functionHashes: {
      'allowance(address,address)': 'dd62ed3e',
      'approve(address,uint256)': '095ea7b3',
      'approveAndCall(address,uint256,bytes)': 'cae9ca51',
      'balanceOf(address)': '70a08231',
      'balanceOfAt(address,uint256)': '4ee2cd7e',
      'claimTokens(address)': 'df8de3e7',
      'createCloneToken(string,uint8,string,uint256,bool)': '6638c087',
      'destroyTokens(address,uint256)': 'd3ce77fe',
      'enableTransfers(bool)': 'f41e60c5',
      'generateTokens(address,uint256)': '827f32c0',
      'totalSupply()': '18160ddd',
      'totalSupplyAt(uint256)': '981b24d0',
      'transfer(address,uint256)': 'a9059cbb',
      'transferFrom(address,address,uint256)': '23b872dd',
    },
    abiDefinition: [
      {
        constant: false,
        inputs: [
          { name: '_spender', type: 'address' },
          { name: '_value', type: 'uint256' },
        ],
        name: 'approve',
        outputs: [{ name: 'success', type: 'bool' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        constant: true,
        inputs: [],
        name: 'totalSupply',
        outputs: [{ name: 'supply', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function',
      },
      {
        constant: false,
        inputs: [
          { name: '_from', type: 'address' },
          { name: '_to', type: 'address' },
          { name: '_value', type: 'uint256' },
        ],
        name: 'transferFrom',
        outputs: [{ name: 'success', type: 'bool' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        constant: true,
        inputs: [
          { name: '_owner', type: 'address' },
          { name: '_blockNumber', type: 'uint256' },
        ],
        name: 'balanceOfAt',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function',
      },
      {
        constant: false,
        inputs: [
          { name: '_cloneTokenName', type: 'string' },
          { name: '_cloneDecimalUnits', type: 'uint8' },
          { name: '_cloneTokenSymbol', type: 'string' },
          { name: '_snapshotBlock', type: 'uint256' },
          { name: '_transfersEnabled', type: 'bool' },
        ],
        name: 'createCloneToken',
        outputs: [{ name: '', type: 'address' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        constant: true,
        inputs: [{ name: '_owner', type: 'address' }],
        name: 'balanceOf',
        outputs: [{ name: 'balance', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function',
      },
      {
        constant: false,
        inputs: [
          { name: '_owner', type: 'address' },
          { name: '_amount', type: 'uint256' },
        ],
        name: 'generateTokens',
        outputs: [{ name: '', type: 'bool' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        constant: true,
        inputs: [{ name: '_blockNumber', type: 'uint256' }],
        name: 'totalSupplyAt',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function',
      },
      {
        constant: false,
        inputs: [
          { name: '_to', type: 'address' },
          { name: '_value', type: 'uint256' },
        ],
        name: 'transfer',
        outputs: [{ name: 'success', type: 'bool' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        constant: false,
        inputs: [
          { name: '_spender', type: 'address' },
          { name: '_amount', type: 'uint256' },
          { name: '_extraData', type: 'bytes' },
        ],
        name: 'approveAndCall',
        outputs: [{ name: 'success', type: 'bool' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        constant: false,
        inputs: [
          { name: '_owner', type: 'address' },
          { name: '_amount', type: 'uint256' },
        ],
        name: 'destroyTokens',
        outputs: [{ name: '', type: 'bool' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        constant: true,
        inputs: [
          { name: '_owner', type: 'address' },
          { name: '_spender', type: 'address' },
        ],
        name: 'allowance',
        outputs: [{ name: 'remaining', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function',
      },
      {
        constant: false,
        inputs: [{ name: '_token', type: 'address' }],
        name: 'claimTokens',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        constant: false,
        inputs: [{ name: '_transfersEnabled', type: 'bool' }],
        name: 'enableTransfers',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, name: '_from', type: 'address' },
          { indexed: true, name: '_to', type: 'address' },
          { indexed: false, name: '_value', type: 'uint256' },
        ],
        name: 'Transfer',
        type: 'event',
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, name: '_owner', type: 'address' },
          { indexed: true, name: '_spender', type: 'address' },
          { indexed: false, name: '_value', type: 'uint256' },
        ],
        name: 'Approval',
        type: 'event',
      },
    ],
    filename:
      '/Users/lyubo/Desktop/Projects/Status/status-fixes/discover/.embark/contracts/token/MiniMeTokenInterface.sol',
    originalFilename: 'contracts/token/MiniMeTokenInterface.sol',
    path:
      '/Users/lyubo/Desktop/Projects/Status/status-fixes/discover/contracts/token/MiniMeTokenInterface.sol',
    gas: 'auto',
    type: 'file',
    deploy: false,
  },
  code: '',
  runtime_bytecode: '',
  real_runtime_bytecode: '',
  swarm_hash: '',
  gas_estimates: null,
  function_hashes: {
    'allowance(address,address)': 'dd62ed3e',
    'approve(address,uint256)': '095ea7b3',
    'approveAndCall(address,uint256,bytes)': 'cae9ca51',
    'balanceOf(address)': '70a08231',
    'balanceOfAt(address,uint256)': '4ee2cd7e',
    'claimTokens(address)': 'df8de3e7',
    'createCloneToken(string,uint8,string,uint256,bool)': '6638c087',
    'destroyTokens(address,uint256)': 'd3ce77fe',
    'enableTransfers(bool)': 'f41e60c5',
    'generateTokens(address,uint256)': '827f32c0',
    'totalSupply()': '18160ddd',
    'totalSupplyAt(uint256)': '981b24d0',
    'transfer(address,uint256)': 'a9059cbb',
    'transferFrom(address,address,uint256)': '23b872dd',
  },
  abi: [
    {
      constant: false,
      inputs: [
        { name: '_spender', type: 'address' },
        { name: '_value', type: 'uint256' },
      ],
      name: 'approve',
      outputs: [{ name: 'success', type: 'bool' }],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: true,
      inputs: [],
      name: 'totalSupply',
      outputs: [{ name: 'supply', type: 'uint256' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: false,
      inputs: [
        { name: '_from', type: 'address' },
        { name: '_to', type: 'address' },
        { name: '_value', type: 'uint256' },
      ],
      name: 'transferFrom',
      outputs: [{ name: 'success', type: 'bool' }],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: true,
      inputs: [
        { name: '_owner', type: 'address' },
        { name: '_blockNumber', type: 'uint256' },
      ],
      name: 'balanceOfAt',
      outputs: [{ name: '', type: 'uint256' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: false,
      inputs: [
        { name: '_cloneTokenName', type: 'string' },
        { name: '_cloneDecimalUnits', type: 'uint8' },
        { name: '_cloneTokenSymbol', type: 'string' },
        { name: '_snapshotBlock', type: 'uint256' },
        { name: '_transfersEnabled', type: 'bool' },
      ],
      name: 'createCloneToken',
      outputs: [{ name: '', type: 'address' }],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: true,
      inputs: [{ name: '_owner', type: 'address' }],
      name: 'balanceOf',
      outputs: [{ name: 'balance', type: 'uint256' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: false,
      inputs: [
        { name: '_owner', type: 'address' },
        { name: '_amount', type: 'uint256' },
      ],
      name: 'generateTokens',
      outputs: [{ name: '', type: 'bool' }],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: true,
      inputs: [{ name: '_blockNumber', type: 'uint256' }],
      name: 'totalSupplyAt',
      outputs: [{ name: '', type: 'uint256' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: false,
      inputs: [
        { name: '_to', type: 'address' },
        { name: '_value', type: 'uint256' },
      ],
      name: 'transfer',
      outputs: [{ name: 'success', type: 'bool' }],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: false,
      inputs: [
        { name: '_spender', type: 'address' },
        { name: '_amount', type: 'uint256' },
        { name: '_extraData', type: 'bytes' },
      ],
      name: 'approveAndCall',
      outputs: [{ name: 'success', type: 'bool' }],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: false,
      inputs: [
        { name: '_owner', type: 'address' },
        { name: '_amount', type: 'uint256' },
      ],
      name: 'destroyTokens',
      outputs: [{ name: '', type: 'bool' }],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: true,
      inputs: [
        { name: '_owner', type: 'address' },
        { name: '_spender', type: 'address' },
      ],
      name: 'allowance',
      outputs: [{ name: 'remaining', type: 'uint256' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: false,
      inputs: [{ name: '_token', type: 'address' }],
      name: 'claimTokens',
      outputs: [],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: false,
      inputs: [{ name: '_transfersEnabled', type: 'bool' }],
      name: 'enableTransfers',
      outputs: [],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: '_from', type: 'address' },
        { indexed: true, name: '_to', type: 'address' },
        { indexed: false, name: '_value', type: 'uint256' },
      ],
      name: 'Transfer',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: '_owner', type: 'address' },
        { indexed: true, name: '_spender', type: 'address' },
        { indexed: false, name: '_value', type: 'uint256' },
      ],
      name: 'Approval',
      type: 'event',
    },
  ],
}
let MiniMeTokenInterface = new EmbarkJS.Blockchain.Contract(
  MiniMeTokenInterfaceJSONConfig,
)
export default MiniMeTokenInterface
