module.exports = {
"Controlled": require('./Controlled.js').default,
"TestBancorFormula": require('./TestBancorFormula.js').default,
"KyberNetworkProxy": require('./KyberNetworkProxy.js').default,
"ApproveAndCallFallBack": require('./ApproveAndCallFallBack.js').default,
"ERC20Token": require('./ERC20Token.js').default,
"TokenFactory": require('./TokenFactory.js').default,
"TokenController": require('./TokenController.js').default,
"MiniMeTokenInterface": require('./MiniMeTokenInterface.js').default,
"MiniMeTokenFactory": require('./MiniMeTokenFactory.js').default,
"SafeMath": require('./SafeMath.js').default,
"MiniMeToken": require('./MiniMeToken.js').default,
"BancorFormula": require('./BancorFormula.js').default,
"Discover": require('./Discover.js').default,
"DiscoverKyberSwap": require('./DiscoverKyberSwap.js').default,
};